name: ContractPolice public deployment
on:
  push:
    tags:
      - v*
jobs:
  # Publish to NPM Package registry
  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
  # Deploy to Docker Hub
  dockerhub-deploy:
    name: Deploy to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - name: Docker Build & Push to Docker Hub
        uses: mr-smithers-excellent/docker-build-push@v3.1
        with:
          image: rwslinkman/contractpolice
          registry: docker.io
          dockerfile: docker/Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}