# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: ContractPolice build pipeline
on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ master ]
jobs:
  # Build application job
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 11.x, 12.x, 13.x, 14.x]
    steps:
    - uses: actions/checkout@v2
      name: Checkout
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
      name: Clean install dependencies
    - run: npm run build --if-present
      name: Run build script
    - run: npm test
      name: Run mocha tests
      env:
        CI: true